/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pembukuan.gui;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pembukuan.*;

/**
 *
 * @author MS
 */
public class pegawaiMenu extends javax.swing.JFrame {

    /**
     * Creates new form pegawaiMenu
     */
    int id_pegawai;
    DefaultTableModel tab = null;
    String id_barang, jumlah_barang;
    String nama_barang;
    String harga_barang;
    String id_paket, jumlah_paket;
    String nama_paket;
    String harga_paket;
    String status_paket;
    int selRow;
    int[] selCol = new int[5];
    Object value = null;

    String[] status = {"diambil", "menunggu Konfirmasi"};

    void showPaket() {
        try {
            Object[] row = {"ID", "Nama Paket", "Jumlah Barang", "Total Harga"};
            tab = new DefaultTableModel(null, row);
            tabel_paket.setModel(tab);
            ConnectionClass c = new ConnectionClass();
            c.setConnection();
            ConnectionClass d = new ConnectionClass();
            d.setConnection();
            ResultSet rs;
            ResultSet rs1;
            rs = c.statement.executeQuery("select * from paket where jumlah_barang > 0");
            System.out.println("aa");
            while (rs.next()) {
                System.out.println("bb");

                rs1 = d.statement.executeQuery("select * from paket_ambil where id_paket='" + rs.getString("id") + "'");

                if (!rs1.next()) {
                    id_paket = rs.getString("id");
                    nama_paket = rs.getString("nama_paket");
                    jumlah_paket = rs.getString("jumlah_barang");
                    harga_paket = rs.getString("harga");
                    String[] data = {id_paket, nama_paket, jumlah_paket, harga_paket};
                    tab.addRow(data);
                    System.out.println("aaa");
                }
            }
            System.out.println("Membaca table Paket");
        } catch (Exception e) {
            System.out.println("gagal ");
            System.out.println(e.getCause());
            System.out.println(e.getMessage());
        }
    }

    void showPenjualan() {
        String id, nama, jumlah, harga;
        try {
            Object[] row = {"ID", "Nama Barang", "Jumlah", "Harga"};
            tab = new DefaultTableModel(null, row);
            tabelMasuk.setModel(tab);
            ConnectionClass c = new ConnectionClass();
            c.setConnection();
            ResultSet rs;
            rs = c.statement.executeQuery("select * from tabel_keluar");
            while (rs.next()) {
                id = rs.getString("id_barang");
                nama = rs.getString("nama_barang");
                jumlah = rs.getString("jumlah_barang");
                harga = rs.getString("harga_barang");
                String[] data = {id, nama, jumlah, harga};
                tab.addRow(data);
            }

            System.out.println("Tampilkan Penjualan");
        } catch (Exception e) {
            System.out.println("gagal ");
            System.out.println(e.getCause());
            System.out.println(e.getMessage());
        }
    }

    public pegawaiMenu(int id) {
        initComponents();
        dataPanel.setVisible(true);
        paketPost.setVisible(true);
        detailPaket.setVisible(false);
        konfirmasiPanel.setVisible(false);
        tambahPemasukan.setVisible(false);

        showPaket();

        id_pegawai = id;
        System.out.println(id_pegawai);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        btnMenuData = new javax.swing.JButton();
        btnMenuKonfirmasi = new javax.swing.JButton();
        btnLihat = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        dataPanel = new javax.swing.JPanel();
        paketPost = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_paket = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        lihatDetail = new javax.swing.JButton();
        detailPaket = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelDetailPaket = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        labelPaket = new javax.swing.JLabel();
        kembaliPaket = new javax.swing.JButton();
        konfirmasiPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        insertidpaket = new javax.swing.JTextField();
        tampilbarangpaket = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        paketDiambil = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelBarangPaket = new javax.swing.JTable();
        tambahPemasukan = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelMasuk = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        menuPenjualan = new javax.swing.JPanel();
        hapus_masuk = new javax.swing.JButton();
        tambahMasuk = new javax.swing.JButton();
        editPenjualan = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        namabarang = new javax.swing.JTextField();
        jumlahbarang = new javax.swing.JTextField();
        hargabarang = new javax.swing.JTextField();
        simpanMasuk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMenuData.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnMenuData.setText("Data Post");
        btnMenuData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuDataActionPerformed(evt);
            }
        });

        btnMenuKonfirmasi.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnMenuKonfirmasi.setText("Konfirmasi");
        btnMenuKonfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuKonfirmasiActionPerformed(evt);
            }
        });

        btnLihat.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnLihat.setText("Tambah Pemasukan");
        btnLihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.CardLayout());

        dataPanel.setLayout(new java.awt.CardLayout());

        tabel_paket.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabel_paket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Jenis Paket", "Jumlah Barang", "Harga"
            }
        ));
        jScrollPane1.setViewportView(tabel_paket);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Ambil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lihatDetail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lihatDetail.setText("Lihat Detail");
        lihatDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paketPostLayout = new javax.swing.GroupLayout(paketPost);
        paketPost.setLayout(paketPostLayout);
        paketPostLayout.setHorizontalGroup(
            paketPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paketPostLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paketPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
                    .addGroup(paketPostLayout.createSequentialGroup()
                        .addComponent(lihatDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        paketPostLayout.setVerticalGroup(
            paketPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paketPostLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paketPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(lihatDetail))
                .addContainerGap())
        );

        dataPanel.add(paketPost, "card2");

        tabelDetailPaket.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabelDetailPaket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Jumlah", "Harga"
            }
        ));
        jScrollPane2.setViewportView(tabelDetailPaket);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("ID : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nama Paket : ");

        labelID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelID.setText("234211");

        labelPaket.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelPaket.setText("paket");

        kembaliPaket.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kembaliPaket.setText("Kembali");
        kembaliPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliPaketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout detailPaketLayout = new javax.swing.GroupLayout(detailPaket);
        detailPaket.setLayout(detailPaketLayout);
        detailPaketLayout.setHorizontalGroup(
            detailPaketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPaketLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailPaketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
                    .addGroup(detailPaketLayout.createSequentialGroup()
                        .addGroup(detailPaketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detailPaketLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelID)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelPaket))
                            .addComponent(kembaliPaket))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        detailPaketLayout.setVerticalGroup(
            detailPaketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPaketLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(detailPaketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(labelID)
                    .addComponent(labelPaket))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(kembaliPaket)
                .addContainerGap())
        );

        dataPanel.add(detailPaket, "card3");

        jPanel1.add(dataPanel, "card2");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("ID Paket");

        insertidpaket.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tampilbarangpaket.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tampilbarangpaket.setText("Ok");
        tampilbarangpaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilbarangpaketActionPerformed(evt);
            }
        });

        paketDiambil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Jenis Paket", "Jumlah Barang", "Harga"
            }
        ));
        jScrollPane3.setViewportView(paketDiambil);

        jButton4.setText("Konfirmasi");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tabelBarangPaket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Jumlah", "Harga"
            }
        ));
        jScrollPane4.setViewportView(tabelBarangPaket);

        javax.swing.GroupLayout konfirmasiPanelLayout = new javax.swing.GroupLayout(konfirmasiPanel);
        konfirmasiPanel.setLayout(konfirmasiPanelLayout);
        konfirmasiPanelLayout.setHorizontalGroup(
            konfirmasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(konfirmasiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(konfirmasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
                    .addGroup(konfirmasiPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(insertidpaket, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tampilbarangpaket)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, konfirmasiPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        konfirmasiPanelLayout.setVerticalGroup(
            konfirmasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(konfirmasiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(konfirmasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(insertidpaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tampilbarangpaket))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap())
        );

        jPanel1.add(konfirmasiPanel, "card4");

        tabelMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tabelMasuk);

        jPanel2.setLayout(new java.awt.CardLayout());

        hapus_masuk.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        hapus_masuk.setText("Hapus Data");
        hapus_masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus_masukActionPerformed(evt);
            }
        });

        tambahMasuk.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tambahMasuk.setText("Tambah Data");
        tambahMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahMasukActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPenjualanLayout = new javax.swing.GroupLayout(menuPenjualan);
        menuPenjualan.setLayout(menuPenjualanLayout);
        menuPenjualanLayout.setHorizontalGroup(
            menuPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPenjualanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tambahMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapus_masuk, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        menuPenjualanLayout.setVerticalGroup(
            menuPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPenjualanLayout.createSequentialGroup()
                .addComponent(tambahMasuk)
                .addGap(18, 18, 18)
                .addComponent(hapus_masuk)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        jPanel2.add(menuPenjualan, "card5");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Nama Barang");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Jumlah");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Harga");

        namabarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jumlahbarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        hargabarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        simpanMasuk.setText("Simpan");
        simpanMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanMasukActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editPenjualanLayout = new javax.swing.GroupLayout(editPenjualan);
        editPenjualan.setLayout(editPenjualanLayout);
        editPenjualanLayout.setHorizontalGroup(
            editPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPenjualanLayout.createSequentialGroup()
                .addGroup(editPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namabarang)
                    .addComponent(jumlahbarang)
                    .addComponent(hargabarang, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPenjualanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(simpanMasuk)
                .addContainerGap())
        );
        editPenjualanLayout.setVerticalGroup(
            editPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPenjualanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(namabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jumlahbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(hargabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(simpanMasuk)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jPanel2.add(editPenjualan, "card6");

        javax.swing.GroupLayout tambahPemasukanLayout = new javax.swing.GroupLayout(tambahPemasukan);
        tambahPemasukan.setLayout(tambahPemasukanLayout);
        tambahPemasukanLayout.setHorizontalGroup(
            tambahPemasukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahPemasukanLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );
        tambahPemasukanLayout.setVerticalGroup(
            tambahPemasukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahPemasukanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahPemasukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(tambahPemasukan, "card3");

        jDesktopPane1.setLayer(btnMenuData, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnMenuKonfirmasi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnLihat, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btnMenuData, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMenuKonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(btnLihat)
                .addGap(58, 58, 58))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLihat)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMenuData)
                        .addComponent(btnMenuKonfirmasi)))
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuDataActionPerformed
        // TODO add your handling code here:
        dataPanel.setVisible(true);
        konfirmasiPanel.setVisible(false);
        tambahPemasukan.setVisible(false);

        showPaket();
    }//GEN-LAST:event_btnMenuDataActionPerformed

    private void btnMenuKonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuKonfirmasiActionPerformed
        // TODO add your handling code here:
        dataPanel.setVisible(false);
        konfirmasiPanel.setVisible(true);
        tambahPemasukan.setVisible(false);
        Object[] row = {"ID", "Nama Paket", "Jumlah Barang", "Total Harga", "Status"};
        tab = new DefaultTableModel(null, row);
        paketDiambil.setModel(tab);
        try {

            ConnectionClass c = new ConnectionClass();
            c.setConnection();
            ConnectionClass d = new ConnectionClass();
            d.setConnection();
            ResultSet rs;
            ResultSet rs1;
            rs = c.statement.executeQuery("select * from paket_ambil where id_pegawai='" + id_pegawai + "'");
            System.out.println("aa");
            while (rs.next()) {
                System.out.println("bb");

                rs1 = d.statement.executeQuery("select * from paket where id='" + rs.getString("id_paket") + "'");

                if (rs1.next()) {
                    id_paket = rs1.getString("id");
                    nama_paket = rs1.getString("nama_paket");
                    jumlah_paket = rs1.getString("jumlah_barang");
                    harga_paket = rs1.getString("harga");
                    status_paket = rs.getString("status_paket");
                    String[] data = {id_paket, nama_paket, jumlah_paket, harga_paket, status_paket};
                    tab.addRow(data);
                    System.out.println("aaa");
                }
            }
            System.out.println("Membaca paket diambil");
        } catch (Exception e) {
            System.out.println("gagal ");
            System.out.println(e.getCause());
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnMenuKonfirmasiActionPerformed

    private void btnLihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatActionPerformed
        // TODO add your handling code here:
        dataPanel.setVisible(false);
        konfirmasiPanel.setVisible(false);
        tambahPemasukan.setVisible(true);

        String id, nama, jumlah, harga;
        try {
            Object[] row = {"ID", "Nama Barang", "Jumlah", "Harga"};
            tab = new DefaultTableModel(null, row);
            tabelMasuk.setModel(tab);
            ConnectionClass c = new ConnectionClass();
            c.setConnection();
            ResultSet rs;
            rs = c.statement.executeQuery("select * from tabel_keluar");
            while (rs.next()) {
                id = rs.getString("id_barang");
                nama = rs.getString("nama_barang");
                jumlah = rs.getString("jumlah_barang");
                harga = rs.getString("harga_barang");
                String[] data = {id, nama, jumlah, harga};
                tab.addRow(data);
            }

            System.out.println("Tampilkan Penjualan");
        } catch (Exception e) {
            System.out.println("gagal ");
            System.out.println(e.getCause());
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnLihatActionPerformed

    private void tambahMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahMasukActionPerformed
        // TODO add your handling code here:

        int idpilih = Integer.parseInt(JOptionPane.showInputDialog(null, "Masukkan ID Barang : "));

        if (idpilih != 0) {
            String id, nama, jumlah, harga;
            try {
                Object[] row = {"ID", "Nama Barang", "Jumlah", "Harga"};
                tab = new DefaultTableModel(null, row);
                tabelMasuk.setModel(tab);
                ConnectionClass c = new ConnectionClass();
                c.setConnection();
                ConnectionClass d = new ConnectionClass();
                d.setConnection();
                ResultSet rs;
                //cek apakah ada pada data pembelian
                rs = c.statement.executeQuery("select * from tabel_masuk where id_barang = '" + idpilih + "'");
                if (rs.next()) {
                    //masukkan data
                    d.statement.executeUpdate("insert into tabel_keluar values("
                            + "'" + rs.getString("id_barang") + "',"
                            + "'" + rs.getString("nama_barang") + "',"
                            + "'" + rs.getString("jumlah_barang") + "',"
                            + "'" + rs.getString("harga_barang") + "'"
                            + ")");
                }
                //reload tabel
                showPenjualan();
                System.out.println("Edit gan");
            } catch (Exception e) {
                System.out.println("gagal ");
                System.out.println(e.getCause());
                System.out.println(e.getMessage());
            }

        }
    }//GEN-LAST:event_tambahMasukActionPerformed

    private void simpanMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanMasukActionPerformed
        // TODO add your handling code here:
        editPenjualan.setVisible(false);
        menuPenjualan.setVisible(true);


    }//GEN-LAST:event_simpanMasukActionPerformed

    private void lihatDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatDetailActionPerformed
        // TODO add your handling code here:
        int idpilih = Integer.parseInt(JOptionPane.showInputDialog(null, "Masukkan ID Paket : "));

        if (idpilih != 0) {
            paketPost.setVisible(false);
            detailPaket.setVisible(true);

            try {
                Object[] row = {"ID", "Nama Barang", "Jumlah", "Harga"};
                tab = new DefaultTableModel(null, row);
                tabelDetailPaket.setModel(tab);
                ConnectionClass c = new ConnectionClass();
                c.setConnection();
                ResultSet rs;
                rs = c.statement.executeQuery("select id, nama_paket from paket where id = '" + idpilih + "'");
                while (rs.next()) {
                    labelID.setText(rs.getString("id"));
                    labelPaket.setText(rs.getString("nama_paket"));
                }
                rs = c.statement.executeQuery("select * from barang where id_paket = '" + idpilih + "'");
                while (rs.next()) {
                    id_barang = rs.getString("id");
                    nama_barang = rs.getString("nama_barang");
                    jumlah_barang = rs.getString("jumlah_barang");
                    harga_barang = rs.getString("harga_barang");
                    String[] data = {id_barang, nama_barang, jumlah_barang, harga_barang};
                    tab.addRow(data);
                }
                System.out.println("Membaca table Paket");
            } catch (Exception e) {
                System.out.println("gagal ");
                System.out.println(e.getCause());
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_lihatDetailActionPerformed

    private void kembaliPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliPaketActionPerformed
        // TODO add your handling code here:
        paketPost.setVisible(true);
        detailPaket.setVisible(false);
    }//GEN-LAST:event_kembaliPaketActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int idpilih = Integer.parseInt(JOptionPane.showInputDialog(null, "Masukkan ID Paket : "));

        if (idpilih != 0) {
            try {
                ConnectionClass c = new ConnectionClass();
                c.setConnection();
                ResultSet rs;
                rs = c.statement.executeQuery("select id from paket where id = '" + idpilih + "'");
                if (!rs.next()) {
                    return;
                }
                c.statement.executeUpdate("INSERT into paket_ambil values("
                        + "'" + id_pegawai + "', "
                        + "'" + idpilih + "', "
                        + "'" + status[0] + "' "
                        + ")");
                showPaket();
                System.out.println("Ambil Paket");
            } catch (Exception e) {
                System.out.println("gagal ");
                System.out.println(e.getCause());
                System.out.println(e.getMessage());
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tampilbarangpaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilbarangpaketActionPerformed
        // TODO add your handling code here:
        Object[] row = {"ID", "Nama Barang", "Jumlah", "Harga"};
        tab = new DefaultTableModel(null, row);
        tabelBarangPaket.setModel(tab);
        String idd = insertidpaket.getText();
        try {
            ConnectionClass c = new ConnectionClass();
            c.setConnection();
            ResultSet rs;
            rs = c.statement.executeQuery("select * from barang where id_paket = '" + idd + "'");
            while (rs.next()) {
                id_barang = rs.getString("id");
                nama_barang = rs.getString("nama_barang");
                jumlah_barang = rs.getString("jumlah_barang");
                harga_barang = rs.getString("harga_barang");
                String[] data = {id_barang, nama_barang, jumlah_barang, harga_barang};
                tab.addRow(data);
            }
            System.out.println("Membaca table barang");
        } catch (Exception e) {
            System.out.println("gagal ");
            System.out.println(e.getCause());
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_tampilbarangpaketActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        try {
            ConnectionClass c = new ConnectionClass();
            c.setConnection();
            ResultSet rs;
            rs = c.statement.executeQuery("select id from paket where id = '" + insertidpaket.getText() + "'");
            if (!rs.next()) {
                return;
            }
            c.statement.executeUpdate("UPDATE paket_ambil SET "
                    + "status_paket = '" + status[1] + "' "
                    + "where id_paket = '" + insertidpaket.getText() + "' and id_pegawai ='" + id_pegawai + "'");
            showPaket();
            System.out.println("konfirmasi");
        } catch (Exception e) {
            System.out.println("gagal ");
            System.out.println(e.getCause());
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void hapus_masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus_masukActionPerformed
        // TODO add your handling code here:
        int idpilih = Integer.parseInt(JOptionPane.showInputDialog(null, "Masukkan ID Barang : "));

        if (idpilih != 0) {
            String id, nama, jumlah, harga;
            try {
                Object[] row = {"ID", "Nama Barang", "Jumlah", "Harga"};
                tab = new DefaultTableModel(null, row);
                tabelMasuk.setModel(tab);
                ConnectionClass c = new ConnectionClass();
                c.setConnection();
                ConnectionClass d = new ConnectionClass();
                d.setConnection();
                ResultSet rs;
                //cek apakah ada pada data pembelian
                rs = c.statement.executeQuery("select * from tabel_masuk where id_barang = '" + idpilih + "'");
                if (rs.next()) {
                    //masukkan data
                    d.statement.executeUpdate("delete from tabel_keluar where id_barang = '" + idpilih + "'");
                }
                //reload tabel
                showPenjualan();
                System.out.println("Edit gan");
            } catch (Exception e) {
                System.out.println("gagal ");
                System.out.println(e.getCause());
                System.out.println(e.getMessage());
            }

        }
    }//GEN-LAST:event_hapus_masukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pegawaiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pegawaiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pegawaiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pegawaiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new pegawaiMenu(int id).setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLihat;
    private javax.swing.JButton btnMenuData;
    private javax.swing.JButton btnMenuKonfirmasi;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JPanel detailPaket;
    private javax.swing.JPanel editPenjualan;
    private javax.swing.JButton hapus_masuk;
    private javax.swing.JTextField hargabarang;
    private javax.swing.JTextField insertidpaket;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jumlahbarang;
    private javax.swing.JButton kembaliPaket;
    private javax.swing.JPanel konfirmasiPanel;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelPaket;
    private javax.swing.JButton lihatDetail;
    private javax.swing.JPanel menuPenjualan;
    private javax.swing.JTextField namabarang;
    private javax.swing.JTable paketDiambil;
    private javax.swing.JPanel paketPost;
    private javax.swing.JButton simpanMasuk;
    private javax.swing.JTable tabelBarangPaket;
    private javax.swing.JTable tabelDetailPaket;
    private javax.swing.JTable tabelMasuk;
    private javax.swing.JTable tabel_paket;
    private javax.swing.JButton tambahMasuk;
    private javax.swing.JPanel tambahPemasukan;
    private javax.swing.JButton tampilbarangpaket;
    // End of variables declaration//GEN-END:variables
}
